# Automatically creates draft of the release as Pull Requests are merged into "master"
# The documentation at https://github.com/release-drafter/release-drafter

name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
